#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
WayTero -- Fix Stuck COMPLETED Bookings
========================================
Purpose: Some bookings have payment_mode set (payment collected) but
         invoice_number is still NULL. This script fixes that on startup.

Idempotent -- safe to run on every backend restart.
Doc Ref: BRD Part 3 S45 -- post-payment state integrity
"""

import asyncio
import os
import sys
from datetime import date

# Force UTF-8 stdout so Windows cp1252 terminal does not crash on special chars
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# Bootstrap path
_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _BACKEND_DIR)

from dotenv import load_dotenv
load_dotenv(os.path.join(_BACKEND_DIR, ".env"))

from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from sqlalchemy import text
from app.core.config import settings


async def run():
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as db:
        print("[fix_stuck] Checking for bookings with payment recorded but missing invoice...")

        result = await db.execute(text("""
            SELECT cb.id, cb.booking_number, cb.booking_status, cb.payment_mode,
                   cb.invoice_number, cb.master_booking_id
            FROM cab_bookings cb
            WHERE cb.payment_mode IS NOT NULL
              AND cb.invoice_number IS NULL
        """))
        rows = result.mappings().all()

        if not rows:
            print("[fix_stuck] OK - No stuck bookings found. All good.")
            await engine.dispose()
            return

        print(f"[fix_stuck] Found {len(rows)} booking(s) needing fix.")

        count_result = await db.execute(text(
            "SELECT COUNT(*) FROM cab_bookings WHERE invoice_number IS NOT NULL"
        ))
        base_count = count_result.scalar() or 0

        today = date.today()
        fixed = 0

        for i, row in enumerate(rows):
            cb_id      = row["id"]
            bn         = row["booking_number"]
            mode       = row["payment_mode"]
            status     = row["booking_status"]
            master_id  = row["master_booking_id"]

            print(f"  [{i+1}] {bn}: status={status}, payment_mode={mode}, invoice=None")

            seq         = base_count + i + 1
            invoice_num = f"WT-INV-{today.strftime('%Y%m')}-{str(seq).zfill(5)}"
            print(f"       -> Assigning invoice_number: {invoice_num}")

            await db.execute(
                text("UPDATE cab_bookings SET invoice_number = :inv WHERE id = :id"),
                {"inv": invoice_num, "id": cb_id},
            )

            await db.execute(text("""
                INSERT INTO booking_timelines
                    (master_booking_id, event_type, event_description, event_timestamp)
                VALUES (:mid, 'INVOICE_AUTO_GENERATED', :desc, NOW())
                ON CONFLICT DO NOTHING
            """), {
                "mid":  master_id,
                "desc": f"Invoice {invoice_num} auto-generated by startup fix for {bn}. Mode: {mode}.",
            })

            fixed += 1

        await db.commit()
        print(f"[fix_stuck] Fixed {fixed} booking(s). Done.")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(run())
